
louvre_booking_home:
    path:      /{page}
    defaults:
        _controller: LouvreBookingBundle:Booking:index
        page:        1
    requirements:
        page: \d*

louvre_booking_page:
    path:     /booking
    defaults:
        _controller: LouvreBookingBundle:Booking:booking

louvre_booking_update:
    path:    /update/{birthdate}
    defaults:
        _controller: LouvreBookingBundle:Booking:update
        birthdate: 01/01/1970
    requirements:
        birthdate: \birthdate+