services:
    louvre_booking.ratechoice:
        class: Louvre\BookingBundle\RateChoice\LouvreRateChoice

#    louvre_booking.example:
#        class: Louvre\BookingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Louvre\BookingBundle\Stripe\StripeClient:
        autowire: true
        autoconfigure: true
        lazy: true

    my.stripe.client:
        alias: Louvre\BookingBundle\Stripe\StripeClient