<?php

namespace Louvre\BookingBundle\Repository;

/**
 * OrderOfTicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderOfTicketsRepository extends \Doctrine\ORM\EntityRepository
{
}
