<?php

namespace Louvre\BookingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTickets($orderId, $orderHolderId)
    {
        $tickets = $this->createQueryBuilder('t')
            ->innerJoin('t.visitor', 'visitor',
                'WITH',
                't.orderOfTickets = :id')
            ->addSelect('visitor')
            ->setParameter('id', $orderId
            );

        return $tickets = $tickets
            ->getQuery()
            ->getArrayResult();
    }
}
