<?php

namespace Louvre\BookingBundle\Repository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{

    //récupérer tous les visiteurs qui appartiennent à des tickets
    // sauf le titulaire de la commande

    public function getVisitors($orderId, $orderHolderId){
        $visitors = $this->createQueryBuilder('v')
            ->select('v.amount')
            ->where('v.id = :id')
            ->setParameters(['id' => $orderId,
                             'visitorId' => $orderHolderId
            ]);
        return $visitors = $visitors
                ->getQuery()
                ->getArrayResult();

    }



}
