<?php
/**
 * Created by PhpStorm.
 * User: delphinemillotpedrero
 * Date: 10/04/2018
 * Time: 17:44
 */

namespace Louvre\BookingBundle\Stripe;

use Flosch\Bundle\StripeBundle\Stripe\StripeClient as BaseStripeClient;

class StripeClient extends BaseStripeClient
{
    public function __construct($stripeApiKey = '') {
        parent::__construct($stripeApiKey);
        return $this;
    }

    public function createCharge($chargeAmount, $chargeCurrency, $paymentToken, $stripeAccountId = null, $applicationFee = 0, $chargeDescription = '', $chargeMetadata = [])
    {
        /* $chargeAmount (int)              : The charge amount in cents, for instance 1000 for 10.00 (of the currency)
         * $chargeCurrency (string)         : The charge currency (for instance, "eur")
         * $paymentToken (string)           : The payment token obtained using the Stripe.js library
         * $stripeAccountId (string|null)   : (optional) The connected string account ID, default null (--> charge to the platform)
         *  (int)            : The amount of the application fee (in cents), default to 0
         * $chargeDescription (string)      : (optional) The charge description for the customer
        */

        return parent::createCharge($chargeAmount, 'eur', $paymentToken, $stripeAccountId, $applicationFee, 'billetterie du musée du Louvre', $chargeMetadata); // Change the autogenerated stub
    }



}